version: "3"
services:
  db:
    image: postgres
    volumes:
      - /Users/amberaftab/Library/Application\ Support/Postgres/var-13:/var/lib/postgresql/data
      - audio_volume:/audiodata/
    environment:
      - POSTGRES_DB=speechtotask
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyPostgresPassword
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - "5555"
    ports:
      - "5555:5555"
    command: -p 5555

  web:
    tty: true
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
      - audio_volume:/audiodata/
      - ./certs:/certs/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - migration
      - db
  migration:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  audio_volume: {}
