# Generated by Django 3.2.5 on 2021-12-02 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(blank=True)),
                ('prompt', models.CharField(max_length=200)),
                ('voice_record', models.FileField(upload_to='speechtotask/audio/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('userObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speechtotask.recording')),
            ],
        ),
    ]
